#Sarah Martin C00257967
#Makefile for hellothreads.cpp and semaphore.cpp 


CC=g++
CFLAGS= -std=c++11 -pthread

THREADS: helloThreads.cpp
	g++ -std=c++11 -pthread helloThreads.cpp Semaphore.cpp -o Threads 


CLEAN:
	rm *.o
